name: ci
on:
  workflow_dispatch:
    branches:
      - main



jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        id: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: docker-login
        id: docker-login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PASS}}

      - name: setup
        run: |
          ## setting and exporting TAG_VERSION environment variable
          GITHUB_SHA=${{github.sha}}
          GITHUB_RUN_ID=${{github.run_id}}
          echo "TAG_VERSION=${GITHUB_SHA::8}-${GITHUB_RUN_ID}" >> ${GITHUB_ENV}

          ## creating a exclusive build folder, because buildkit don't support subdirs, yet
          ln -s src/python/alpine/ .build
          pwd && ls -l
          ls -l .build/

      - name: build
        uses: docker/build-push-action@v3.2.0
        with:
          file: .build/Dockerfile
          build-args: |
            IMAGE_NAME=python-alpine
            IMAGE_VERSION=${{env.TAG_VERSION}}
            IMAGE_ARCHITECTURE=x86_64
            OS_NAME="Alpine Linux"
            OS_VERSION="3.17.0"
            KERNEL_VERSION="6.0.12-arch1-1"
            LICENSE=""
            BUILD_DATE=$(TZ="America/Sao_Paulo" date +'%Y-%m-%dT%H:%M:%SZ')
            VCS_REF=$(git rev-parse --short HEAD)
            VCS_URL=""
            IMAGE_MAINTAINER="acardoso.devops@gmail.com"
            IMAGE_VENDOR="Groking Labs"
            IMAGE_SCHEMA_VERSION="1.0"
            IMAGE_USAGE=""
            IMAGE_URL=""
            IMAGE_DESCRIPTION="Badass base image for python projects"
            DOCKER_CMD=""
            DOCKER_CMD_DEBUG=""
            DOCKER_CMD_HELP=""
            DOCKER_CMD_DEVEL=""
            DOCKER_CMD_TEST=""
            DOCKER_PARAMS=""
          tags: |
            aleroxac/python-alpine:${{env.TAG_VERSION}}
          context: .build
          push: true

# scan-image
# promote-image
# push-image
