version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: ".github/workflows"
    schedule:
      interval: "daily"
      timezone: "America/Sao_Paulo"
      time: "07:00"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      timezone: "America/Sao_Paulo"
      time: "07:00"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      timezone: "America/Sao_Paulo"
      time: "07:00"
