name: release-python-alpine



on:
  push:
    tags:
      - "v*"



jobs:
  release:
    runs-on: ubuntu-latest
    name: Bump new version
    steps:
      - name: update-version-references
        run:
          python scripts/update-versionrefs.py

      - name: bump-version
        id: bump-version
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true

      - name: push-images
        uses: ./.github/workflows/ci.yml
        with:
          push: true
          image-ref: 'harbor.home.lab/images/${{matrix.IMAGE_NAME}}:${{env.TAG_VERSION}}-${{matrix.IMAGE_BASE}}'
          tags: |
            harbor.home.lab/images/${{matrix.IMAGE_NAME}}:${{env.TAG_VERSION}}-${{matrix.IMAGE_BASE}}
